### ISSUE TITLE
Error in drying to drop column that doesn't exist.

### ISSUE THREAD

**Issue by erinyoung** [DrB-S/HeatCluster#40]
HeatCluster is throwing an error:

```
/workspace/heatcluster/heatcluster.py:55: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  if len(tabs.columns) > len(commas.columns):
Traceback (most recent call last):
  File "/workspace/heatcluster/heatcluster.py", line 163, in <module>
    main(args)
  File "/workspace/heatcluster/heatcluster.py", line 42, in main
    df = clean_and_read_df(df)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/heatcluster/heatcluster.py", line 65, in clean_and_read_df
    df = df.drop("0")
         ^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/polars/dataframe/frame.py", line 7278, in drop
    return self.lazy().drop(*columns, strict=strict).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/polars/lazyframe/frame.py", line 2027, in collect
    return wrap_df(ldf.collect(callback))
                   ^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: "0" not found
```

The SNP matrix can be found in this issue:

https://github.com/UPHL-BioNGS/Grandeur/issues/221

**Comment by DrB-S** [comment]
Where would I insert 'LazyFrame.collect_schema().names()' as suggested in the error above? And would I remove 'df = df.drop("0")'?
